config/routes.rb
Rails.application.routes.draw do
  get "comments/new"

  get "posts/create"

  get "posts/new"

  devise_for :users

  resources :posts do
    collection do
      get :search
    end
    resources :comments
    resources :charges
  end

  root to: "posts#index"

  resources :tags do
    resources :posts
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
  belongs_to :user
  has_and_belongs_to_many :tags
  
  has_attached_file :image, 
                    styles: { thumb: "400x400>", medium: '500x500>' },
                    storage: :s3,
                    s3_credentials: {
                      access_key_id: 'AKIAJ57EWJKMPW4556TA',
                      secret_access_key: Rails.application.secrets.s3_secret
                    },
                    bucket: 'hipstagram_development'

  def tag_names
    tags.map { |tag| tag.name }.join(', ')
  end

  def tag_names=(tag_names)
    self.tags = Tag.find_or_create_from_tag_names(tag_names)
  end

  def self.display_by_tags_or_all(tag_name)
    tag_name ? Tag.find_by(name: tag_name).posts : Post.all
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :posts

  #callback
  before_validation :format_name

  def to_s
    '#' + name
  end

  def to_param
    name
  end

  def self.find_or_create_from_tag_names(tag_names)
    tag_names.split(/,\s?/).map do |tag|
      find_or_create_by(:name => tag)
    end
  end

  private

  def format_name
    self.name = name.downcase.gsub(/[^a-z]/, '')
  end 

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :comments
  has_many :posts
    
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
    @post = Post.find(params[:post_id])
  end

  def create
    @amount = 1000
    @post = Post.find(params[:post_id])

    customer = Stripe::Customer.create(
      :email => current_user.email
      :card  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => "Print of" + @post.title
      :currency    => 'gbp'
    )

    flash[:alert] = "Thanks for you support!"
    redirect_to post_path(@post)
    # Order.create(:user => current_user, :amount => @amount)


  rescue Stripe::CardError => e
    flash[:error] = "Something went wrong with your payment"
    redirect_to post_path(@post)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :authenticate_user!

  def new
    @post = Post.find(params[:post_id])
    @comment = Comment.new
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = Comment.new(params[:comment].permit(:text))
    @comment.post_id = @post.id

    @comment.user = current_user

    if @comment.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def index
    @post = Post.find(params[:post_id])
    render json: @post.comments.to_json
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_user!, only: [:new, :update]
  
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(params[:post].permit(:title, :content, :image, :tag_names))
    @post.user = current_user

    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def index
    @posts = Post.display_by_tags_or_all(params[:tag_id])
  end

  def edit
    @post = current_user.posts.find(params[:id])
  end

  def update
    @post = current_user.posts.find(params[:id])
    
    if @post.update(params[:post].permit(:title, :content, :image, :tag_names))
      redirect_to '/posts'
    else
      render 'edit'
    end
  end

  def destroy
    @post = current_user.posts.find(params[:id])

    @post.destroy

    redirect_to '/posts'
  end

  def search
    @posts = Post.where('title ILIKE ?', "%#{params[:query]}%")
    render 'index'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>£10</strong>!</h2>

app/views/comments/new.html.erb
<%= form_for [@post, @comment] do |f| %>

  <%= f.label :text %>
  <%= f.text_area :text %>

  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hipstagram</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body data-no-turbolink>
  <%= render 'shared/nav' %>

  <%= bootstrap_flash %>
  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/posts/_post.html.erb
<div class='col-md-6'>
  <div class='row'>
    <div class='col-md-10'>
        <h2><%= link_to post.title, post %></h2>
    </div>
    <% if post.user == current_user %>
      <div class='col-md-2 delete'>
        <span class='delete-link'>
          <%= link_to '✖', post_path(post), method: :delete, data: { confirm: "Are you sure?" } %>
        </span>
       </div>
     <% end %>
  </div>
  <div class='row'>
    <div class='col-md-12'>
      <p>
        <%= post.content %>
      </p>
    </div>
  </div>
  <div class='row'>
    <div class='col-md-12'>
      <%= image_tag post.image.url(:thumb), class: 'instagram-upload' %>
    </div>
  </div>
  <div class='row tags'>
    <div class='col-md-6'>
      <% post.tags.each do |tag| %>
        <%= link_to tag, tag_posts_path(tag) %>
      <% end %>
    </div>
    <div class='col-md-6 favourite'>
      <span class='heart'>♡</span>
    </div>
  </div>
  <% if post.user == current_user %>
    <div class='row admin-box'>
      <div class='col-md-6'>
        <span class='admin edit-links'>
          <%= link_to 'Edit', edit_post_path(post) %>
          <%= link_to 'Add comment', new_post_comment_path(post) %>
          <%= link_to 'Add tag', edit_post_path(post) %>
        </span>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/edit.html.erb
<%= form_for @post, html: { multipart: true }  do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <br />
  <hr>

  <%= f.label :content %>
  <%= f.text_area :content %>

  <br />
  <hr>

  <%= f.label :image %>
  <%= f.file_field :image %>

  <br />
  <hr>
  <p>Please enter tags separated by comma:</p>
  <%= f.label :tag_names %>
  <%= f.text_area :tag_names, id: 'tag-input' %>

  <br />
  <hr>

  <%= f.submit %>
<% end %>

app/views/posts/index.html.erb
<div class='row post'>
  <%= @posts.any? ? render(@posts) : 'There are no photo yet! Please add some.' %>
</div>

app/views/posts/new.html.erb
<%= form_for @post, html: { multipart: true } do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <br />
  <hr>

  <%= f.label :content %>
  <%= f.text_area :content %>

  <br />
  <hr>

  <%= f.label :image %>
  <%= f.file_field :image %>

  <br />
  <hr>
  <p>Please enter tags separated by comma:</p>
  <%= f.label :tag_names, for: 'tag-input' %>
  <%= f.text_area :tag_names, id: 'tag-input' %>

  <br />
  <hr>

  <%= f.submit %>
<% end %>

app/views/posts/show.html.erb
<div class='row'>

  <div class='col-md-10'>
      <h2><%= link_to @post.title, @post %></h2>
  </div>
  <div class='col-md-2 delete'>
    <span class='delete-link'>
      <%= link_to '✖', post_path(@post), method: :delete, data: { confirm: "Are you sure?" } %>
    </span>
   </div>
</div>

<div class='row'>
  <div class='col-md-12'>
    <p>
      <%= @post.content %>
    </p>
  </div>
</div>

<div class='row'>
  <div class='col-md-6'>
    <%= image_tag @post.image.url(:thumb), class: 'instagram-upload' %>
  </div>
</div>

<div class='row tags'>
  <div class='col-md-4'>
    <% @post.tags.each do |tag| %>
      <%= link_to tag, tag_posts_path(tag) %>
      <% end %>
    <%= link_to 'Add comment', new_post_comment_path(@post), class: 'color: grey' %>
  </div>
  <div class='col-md-2 favourite'>
    hi
  </div>
</div>
<% if @post.user == current_user %>
  <div class='row admin-box'>
    <div class='col-md-6'>
      <span class='admin edit-links'>
        <%= link_to 'Edit', edit_post_path(@post) %>
        <%= link_to 'Add tag', edit_post_path(@post) %>
      </span>
    </div>
  </div>
<% end %>
<% if @post.comments.any? %>
  <div class='col-md-6'>
    <div class='row comments'> 
        <%= link_to 'Show comments', '#', data: { url: post_comments_path(@post, format: :json) }, class: 'btn btn-success show-comments' %>
      </div>
      <div class='spinner'>
        <img src='http://www.iab.net/extra/adquickref/spinnerLarge.gif'>
      </div>
        <script type='text/template' id='comment-template'>
           <div class='well'>
            <h4>{{ commenter }}</h4>
            <p>{{ text }}</p>
          </div>
        </script>
        <div class='comments-container'></div>
  </div>
<% end %>

<div class='row'>
  <div class='col-md-12'>
    <h4>Buy as a print!</h4>
    <%= form_tag post_charges_path(@post) do %>
      <script
        src="https://checkout.stripe.com/checkout.js" class="stripe-button"
        data-key="pk_test_4VBdirVmOW1BeZ8HGACAgSrd"
        data-name="<%= @post.title%>"
        data-amount="1000"
        data-currency="gbp">
      </script>
    <% end %>
  </div>
</div>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-default navbar-fixed-top nagivation" role="navigation">
  <div id='nav-bar'>
    <ul class="nav navbar-nav">
      <% if user_signed_in? %>
        <li>
          <%= link_to 'Hipstagram', root_path, {:class => 'navbar-brand'} %>
        </li>
        <li>
          <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
        </li>
      <% else %>
        <li>
          <%= link_to('Login', new_user_session_path)  %>  
        </li>
      <% end %>
      <% if user_signed_in? %>
        <li>
          <%= link_to('Edit registration', edit_user_registration_path) %>
        </li>
      <% else %>
        <li>
          <%= link_to('Register', new_user_registration_path)  %>
        </li>
      <% end %>
      <li>
        <%= link_to 'Add photo', new_post_path, { :style => "color:green" } %>
      </li>
    </ul>
    <div class="form-group">
      <%= form_tag search_posts_path, role: 'search', class: 'navbar-form navbar-left', method: :get do %>
          <%= text_field_tag :query, nil, id: 'search' %>
          <%= submit_tag 'Search' %>
      <% end %>
    </div>
  </div>
</nav>